version: "3"

services:
  app:
    container_name: my-ng-sample-app
    build:
      context: ./
      dockerfile: Dockerfile
    # environment:
    #   - REACT_APP_ENV=production
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 4000:4000
    restart: always
